// <auto-generated />
using System;
using CodeSnifferDog.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CodeSnifferDog.Server.Migrations
{
    [DbContext(typeof(CodeSnifferDogServerDbContext))]
    [Migration("20260519022605_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CodeSnifferDog.Server.Data.Entities.ProjectAgentGroupRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("RuntimeKey")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId", "CreatedAtUtc");

                    b.HasIndex("ProjectId", "RuntimeKey")
                        .IsUnique();

                    b.ToTable("ProjectAgentGroups", (string)null);
                });

            modelBuilder.Entity("CodeSnifferDog.Server.Data.Entities.ProjectAgentRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ProjectAgentGroupId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("RuntimeKey")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProjectAgentGroupId", "CreatedAtUtc");

                    b.HasIndex("ProjectAgentGroupId", "RuntimeKey")
                        .IsUnique();

                    b.ToTable("ProjectAgents", (string)null);
                });

            modelBuilder.Entity("CodeSnifferDog.Server.Data.Entities.ProjectAgentTimelineEntryRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("EntryType")
                        .HasColumnType("int");

                    b.Property<string>("Message")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("OccurredAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("ProjectAgentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("Sequence")
                        .HasColumnType("bigint");

                    b.Property<string>("ToolArguments")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ToolCallId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ToolName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ToolResult")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ProjectAgentId", "OccurredAtUtc");

                    b.HasIndex("ProjectAgentId", "Sequence")
                        .IsUnique();

                    b.HasIndex("ProjectAgentId", "ToolCallId")
                        .IsUnique()
                        .HasFilter("[ToolCallId] IS NOT NULL");

                    b.ToTable("ProjectAgentTimelineEntries", (string)null);
                });

            modelBuilder.Entity("CodeSnifferDog.Server.Data.Entities.ProjectRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("FailureReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("FileSizeBytes")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset?>("FinishedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("OriginalFileName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("ProcessingStartedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("QueueTimestampUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("StoredZipRelativePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("Status", "QueueTimestampUtc", "CreatedAtUtc");

                    b.ToTable("Projects", (string)null);
                });

            modelBuilder.Entity("CodeSnifferDog.Server.Data.Entities.ProjectRuleReportRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("MarkdownContent")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("RuleKey")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RuleKeyHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("RuleName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId", "RuleKeyHash")
                        .IsUnique();

                    b.ToTable("ProjectRuleReports", (string)null);
                });

            modelBuilder.Entity("CodeSnifferDog.Server.Data.Entities.ProjectAgentGroupRecord", b =>
                {
                    b.HasOne("CodeSnifferDog.Server.Data.Entities.ProjectRecord", "Project")
                        .WithMany("AgentGroups")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("CodeSnifferDog.Server.Data.Entities.ProjectAgentRecord", b =>
                {
                    b.HasOne("CodeSnifferDog.Server.Data.Entities.ProjectAgentGroupRecord", "Group")
                        .WithMany("Agents")
                        .HasForeignKey("ProjectAgentGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Group");
                });

            modelBuilder.Entity("CodeSnifferDog.Server.Data.Entities.ProjectAgentTimelineEntryRecord", b =>
                {
                    b.HasOne("CodeSnifferDog.Server.Data.Entities.ProjectAgentRecord", "Agent")
                        .WithMany("TimelineEntries")
                        .HasForeignKey("ProjectAgentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Agent");
                });

            modelBuilder.Entity("CodeSnifferDog.Server.Data.Entities.ProjectRuleReportRecord", b =>
                {
                    b.HasOne("CodeSnifferDog.Server.Data.Entities.ProjectRecord", "Project")
                        .WithMany("RuleReports")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("CodeSnifferDog.Server.Data.Entities.ProjectAgentGroupRecord", b =>
                {
                    b.Navigation("Agents");
                });

            modelBuilder.Entity("CodeSnifferDog.Server.Data.Entities.ProjectAgentRecord", b =>
                {
                    b.Navigation("TimelineEntries");
                });

            modelBuilder.Entity("CodeSnifferDog.Server.Data.Entities.ProjectRecord", b =>
                {
                    b.Navigation("AgentGroups");

                    b.Navigation("RuleReports");
                });
#pragma warning restore 612, 618
        }
    }
}
