using CodeSnifferDog.Models.ProjectPlan;
using CodeSnifferDog.Models.Review;
using CodeSnifferDog.Models.RuleReview;

namespace CodeSnifferDog.Models.Report;

/// <summary>
/// Holds the outputs and execution metadata produced by one report workflow run.
/// </summary>
public sealed class WorkflowResult
{
    /// <summary>
    /// Gets the rule key associated with the report.
    /// </summary>
    public required string RuleKey { get; init; }

    /// <summary>
    /// Gets the task item whose review output was aggregated into the report.
    /// </summary>
    public required StoredTaskItem TaskItem { get; init; }

    /// <summary>
    /// Gets the repository issue diff generated by the report.
    /// </summary>
    public required Diff Diff { get; init; }

    /// <summary>
    /// Gets the full repository issue set after the report was applied.
    /// </summary>
    public required IReadOnlyList<StoredIssue> RepositoryIssues { get; init; }

    /// <summary>
    /// Gets the final review verdict for the report output.
    /// </summary>
    public required ReviewVerdict Verdict { get; init; }

    /// <summary>
    /// Gets whether the workflow continued after exhausting verifier rejection attempts.
    /// </summary>
    public required bool ContinuedAfterVerifierRejectionLimit { get; init; }

    /// <summary>
    /// Gets how many aggregator attempts were executed.
    /// </summary>
    public required int AggregatorAttempts { get; init; }

    /// <summary>
    /// Gets how many verifier attempts were executed.
    /// </summary>
    public required int VerifierAttempts { get; init; }
}
